---

- name: Set variables for CentOS
  set_fact:
    cron_package: "{{ cron_package | default('crontabs') }}"
    cron_service_name: "{{ cron_service_name | default('crond') }}"
  when: ansible_os_family == "RedHat"

- name: Set variables for Debian/Ubuntu
  set_fact:
    cron_package: "{{ cron_package | default('cron') }}"
    cron_service_name: "{{ cron_service_name | default('cron') }}"
  when:
    - ansible_os_family == "Debian"
